### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by rl-pangilinan** [Baggette/Baggette-site#5]
Peaches doesn't work

**Comment by RealMrLBronzey9** [comment]
I have this problem as well. If somebody has the solution please let me know.

**Comment by Baggette** [comment]
I found the issue, but im too lazy to fix right now. I forgot to link the script in the html

**Comment by rl-pangilinan** [comment]
Please share if you find solution

**Comment by RealMrLBronzey9** [comment]
Nvm. I solved it on my own.

**Comment by Baggette** [comment]
Issue resolved

**Comment by Pineappletwo1** [comment]
#cringe?
