### ISSUE TITLE
为什么选择闪光弹

### ISSUE THREAD

**Issue by RealMrLBronzey9** [Baggette/Baggette-site#7]
Website flashbangs me I cant see anymore thanks to this serious bug in the code. The amount of times that white screen shows up everytime I navigate the site. I get immediately flashbanged like my eyes isn't capable of handling this intense white light. This is unplayable I can no longer click on all the links anymore sadly. This serious problem needs to be fixed or someone might be flashbanged too hard. Also thanks for fixing peaches that is amazing. Like this website is soo cool with a FIRE README.md like what pineapple said. If you want to fix this problem please replace the flashbang with something like a instant load or if you DO need to harm the user then use something more powerful and painless. Like a nuke or something. 
![Untitled](https://github.com/Baggette/Baggette-site/assets/117611460/6487d718-4485-4450-af1e-3d17b7da7fd6)

**Comment by Baggette** [comment]
make a pr and add the feature then

**Comment by Pineappletwo1** [comment]
crazy shit

**Comment by Pineappletwo1** [comment]
my eyes!

**Comment by Jwang0506** [comment]
agree
