### ISSUE TITLE
the best ui i have ever seen

### ISSUE THREAD

**Issue by Pineappletwo1** [Baggette/Baggette-site#8]
the ui is so good that it burns my eyes when i try to look at it, the flashbang issue didn't help it either, the ui is not bad, its dog sh*t

**Comment by Jwang0506** [comment]
so good that it fixed my bad vision by making me permanently blind

**Comment by Baggette** [comment]
a8b01ab95a19e76c1f7780d0896db3ab466e950d issue fixed

**Comment by Pineappletwo1** [comment]
cap the ui still looks like crap

**Comment by Baggette** [comment]
> cap the ui still looks like crap

cope
