### ISSUE TITLE
An actual legit issue please fix pretty please

### ISSUE THREAD

**Issue by RealMrLBronzey9** [Baggette/Baggette-site#9]
when home button press it become
**_404 Not Found_**
**Not Found**
The requested URL was not found on this server.
_____________________________________________________________________________

Apache/2.4.55 (Ubuntu) Server at baggette.org Port 80

**Comment by Baggette** [comment]
> when home button press it become **_404 Not Found_** **Not Found** The requested URL was not found on this server.
> 
> Apache/2.4.55 (Ubuntu) Server at baggette.org Port 80

Issue resolved 513687a64cb5f8e7dba03cfe477efac3e460228b

**Comment by RealMrLBronzey9** [comment]
ez
